//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Serilog Contributors")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Serilog Contributors")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Simple .NET logging with fully-structured events")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.3.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("4.3.0-main-726e29c+726e29c5b172aa8813285be1ad8cc728fd531eab")]
[assembly: System.Reflection.AssemblyProductAttribute("Serilog")]
[assembly: System.Reflection.AssemblyTitleAttribute("Serilog")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.3.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/serilog/serilog")]

// Generated by the MSBuild WriteCodeFragment class.

